### ISSUE TITLE
Directory Api's members().hasMember(group, email) returns error "Invalid Input: memberKey"

### ISSUE THREAD

**Issue by vitamon** [googleapis/google-api-java-client#1082]
Call to "hasMembers" returns error
```
{
 "code" : 400,
 "errors" : [ {
  "domain" : "global",
  "message" : "Invalid Input: memberKey",
  "reason" : "invalid"
  } ],
  "message" : "Invalid Input: memberKey"
 }
```

While call to members/get with the same parameters returns good response
```
adminApi().members().get(group, email).execute()
```
Version "directory_v1-rev89-1.23.0"

building api like this (scala)
```
def adminApi() = {
    new Directory.Builder(Utils.getDefaultTransport, Utils.getDefaultJsonFactory, groupsCredential)
      .setApplicationName(gcpProjectId)
      .build
  }
```

**Comment by qaisjp** [comment]
I get a correct response if `memberKey` is within the domain (`qaisjp@betterinformatics.com`) but

```
<HttpError 400 when requesting https://www.googleapis.com/admin/directory/v1/groups/users%40betterinformatics.com/hasMember/qaisjp%40gmail.com?alt=json returned "Invalid Input: memberKey">
```

when I try 

```
directory.members().hasMember(groupKey="users@betterinformatics.com", memberKey='qaisjp@gmail.com').execute()
```

My problem is on Python though, so I think this is a server-side issue :/

It doesn't look like they want us probing whether or not an external email is inside the group, yet doesn't complain if we add external emails to the group...

**Comment by qaisjp** [comment]
I'm getting around this issue by attempting a `directory.members().get(groupKey="users@domain.com", memberKey=email)`, and catching the 404 error if they are not a member.

(This doesn't work for nested members.)

**Comment by vitamon** [comment]
Yeah, but the only reason I use google groups is the ability to add emails from different domains. And I should be able to check it, right? 
I ended up using different endpoint to get all groups for the email address, and it works as expected. adminApi().groups().list().setUserKey(email).execute()

**Comment by Sparticuz** [comment]
I ran into this problem today and posted a bug on the issue tracker
https://issuetracker.google.com/issues/109861216

I also got around it by using list then looping through the results.

**Comment by sduskis** [comment]
It looks like there's a way to get the functionality you need, even though it's not ideal.  I'm going to close this for now, since the question itself is resolved.  If you'd like, please open a new issue for a feature request for a better user experience around this issue.

**Comment by vitamon** [comment]
So finding a workaround now counts as fixing the issue?

**Comment by qaisjp** [comment]
@vitamon in principle I agree with you, but this is not a client problem. (I have had this same issue with Python).

@sduskis, I think it would be best to keep this issue open with an `upstream` label. There's nothing the client can (or should) do, but it's still a problem.

**Comment by vitamon** [comment]
Ah, yes, agree, it is not the client's problem. Not sure where to report the Api issues

**Comment by cemo** [comment]
@sduskis where this issue should be reported? It seems the issue in public issue tracker of google could not get enough attention as always.

**Comment by cemo** [comment]
By the way for those who will hit this issue: you can use `get` instead of `hasMember`, it returns users without looping all members by `list`.

**Comment by sduskis** [comment]
@cemo, I'd start here: https://developers.google.com/admin-sdk/directory/support.  There's the issue tracker, which you tried, and stack overflow.  I wish i had a better answer.

**Comment by sneko** [comment]
Hi @sduskis , are you able to forward the post on issue tracker internally to the right team managing Admin SDK please (no answer on it...)?

I'm in the same situation than others, hasMember() helps a lot to know about members in nested groups, but if trying on a @gmail.com account does not work... it looses all its sense 😢 

And if that's the wanted behavior, it would be great to get some information on why 😃 

Thank you,

**Comment by Sparticuz** [comment]
I already filed a bug upstream last year: https://issuetracker.google.com/issues/109861216

My guess as to why it hasn't been fixed is probably privacy related.

**Comment by sneko** [comment]
@Sparticuz I saw your issue and "upvoted". I was just asking @sduskis if it's possible he pushes it to the right team since he seems to work at Google.

**Comment by KyleJamesWalker** [comment]
@cemo
> By the way for those who will hit this issue: you can use `get` instead of `hasMember`, it returns users without looping all members by `list`.

The only issue with this is it doesn't support nested groups 😢
